version: "3.7"
services:
  pg_master:
    image: sw814f20/pg-master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=Giraf
      - POSTGRES_PASSWORD=Giraf123
      - POSTGRES_DB=giraf
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=Rep123
    networks:
      default:
        aliases:
          - pg_cluster
  pg_slave:
    image: sw814f20/pg-slave
    environment:
      - POSTGRES_USER=Giraf
      - POSTGRES_PASSWORD=Giraf123
      - POSTGRES_DB=giraf
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=Rep123
      - PG_MASTER_HOST=pg_master
    deploy:
      replicas: 3
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data:
